language: java
jdk:
  - oraclejdk8
script: mvn clean verify -Dmaven.compiler.target=1.8 -Dmaven.compiler.source=1.8
deploy:
		- provider: openshift
		user: "mariusz.danielewski@gmail.com"
		password: "manson666"
		skip_cleanup: true
    	clean_up: false
		app: "dev"
		domain: "http://dev-eleave.rhcloud.com"
